/** Optional edge integration tests.
 * node tests/browser_edges.cjs camera.y4m blank.mp4 face-video.mp4
 * Generate camera.y4m and blank.mp4 with FFmpeg; see docs/VALIDATION.md.
 */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const {spawn}=require('node:child_process');
const {mkdtemp,readFile,rm,writeFile,mkdir}=require('node:fs/promises');
const path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const [camera,blank,face]=process.argv.slice(2);
if(!face)throw new Error('Supply camera.y4m, blank.mp4, and face-video.mp4 paths.');
(async()=>{const tmp=await mkdtemp(path.join(os.tmpdir(),'facescope-edges-'));const output=process.env.TEST_OUTPUT||tmp;await mkdir(output,{recursive:true});
const server=spawn(process.env.PYTHON||'python',['run.py','--port','0','--no-browser','--data-dir',tmp],{cwd:path.resolve(__dirname,'..'),stdio:['ignore','pipe','pipe']});
const url=await new Promise(resolve=>server.stdout.on('data',d=>{const m=String(d).match(/http:\/\/127\.0\.0\.1:\d+/);if(m)resolve(m[0]);}));let browser;
try{browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{}),args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--use-file-for-fake-video-capture='+path.resolve(camera)]});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
await page.goto(url);await page.waitForFunction(()=>document.querySelector('#modelStatus').textContent.includes('ready'),null,{timeout:60000});
await page.locator('#rawLandmarks').check();await page.locator('#camera').click();await page.waitForFunction(()=>document.querySelector('#trackingStatus').textContent==='FACE TRACKED',null,{timeout:30000});
let event=page.waitForEvent('download');await page.locator('#json').click();let dl=await event;await dl.saveAs(path.join(tmp,'camera.json'));let session=JSON.parse(await readFile(path.join(tmp,'camera.json'),'utf8'));let detected=session.samples.find(s=>s.detected);assert.equal(detected.landmarks.length,478);assert.equal(detected.transform.length,16);
await page.evaluate(()=>window.testTrack=document.querySelector('#video').srcObject.getVideoTracks()[0]);await page.locator('#stop').click();assert.equal(await page.evaluate(()=>window.testTrack.readyState),'ended');assert.equal(await page.locator('#eyeLeft').textContent(),'—');console.log('Camera flow, raw landmarks, camera release passed.');
await page.locator('#rawLandmarks').uncheck();await page.locator('#fileInput').setInputFiles(blank);await page.waitForFunction(()=>document.querySelector('#batch').disabled===false);await page.locator('#batch').click();await page.waitForFunction(()=>+document.querySelector('#progress').value===100&&document.querySelector('#batch').textContent==='Analyze full video');
event=page.waitForEvent('download');await page.locator('#json').click();dl=await event;await dl.saveAs(path.join(tmp,'blank.json'));session=JSON.parse(await readFile(path.join(tmp,'blank.json'),'utf8'));assert.equal(session.samples.length,15);assert.ok(session.samples.every(s=>!s.detected&&s.eye_left===null&&s.mouth===null));assert.equal(session.events.length,0);console.log('No-face dataset preserves missing values.');
await page.locator('#fileInput').setInputFiles(face);await page.waitForFunction(()=>document.querySelector('#trackingStatus').textContent==='FACE TRACKED',null,{timeout:30000});await page.locator('#batch').click();await page.waitForFunction(()=>+document.querySelector('#progress').value>1&&document.querySelector('#batch').textContent==='Cancel analysis',null,{timeout:30000});await page.locator('#batch').click();await page.waitForFunction(()=>document.querySelector('#batch').textContent==='Analyze full video',null,{timeout:30000});assert.ok(await page.locator('#toast').textContent().then(t=>t.includes('canceled')));
await page.locator('#seek').evaluate(el=>{el.value='50';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Moved to selected frame'),null,{timeout:30000});assert.ok(await page.locator('#time').textContent().then(t=>t.startsWith('00:27')));assert.deepEqual(errors,[]);console.log('Batch cancellation and seeking passed.');
await writeFile(path.join(output,'edge-results.json'),JSON.stringify({passed:true,tests:['fake webcam acquisition','478 raw landmark triplets','16 transform entries','camera track released','no-face null values','no false blink on black video','batch cancel retains partial data','seek starts clean dataset'],page_errors:errors},null,2));
}finally{await browser?.close();server.kill();await rm(tmp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
