import {summarize,toCSV} from './metrics.js';
export function download(data,filename,type='application/json') {
  const url=URL.createObjectURL(new Blob([data],{type}));
  const anchor=document.createElement('a');anchor.href=url;anchor.download=filename;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
}
export const escapeHTML=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function reportHTML(session) {
  const sum=summarize(session.samples,session.events),fmt=n=>Number.isFinite(n)?n.toFixed(3):'—';
  const rows=['eye_left','eye_right','mouth','yaw','pitch','roll','iris_x','iris_y'].map(k=>`<tr><td>${k}</td><td>${fmt(sum[k]?.mean)}</td><td>${fmt(sum[k]?.min)}</td><td>${fmt(sum[k]?.max)}</td></tr>`).join('');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><title>FaceScope · ${escapeHTML(session.name)}</title><style>body{font:15px/1.6 system-ui,sans-serif;max-width:950px;margin:50px auto;padding:0 24px;color:#16313c}h1{font-size:38px;line-height:1.15}small{color:#4e727b}table{border-collapse:collapse;width:100%;margin:25px 0}td,th{text-align:left;border-bottom:1px solid #c6d4d9;padding:10px}.stats{display:flex;gap:30px;flex-wrap:wrap;background:#eff7f5;padding:20px}.stats b{font-size:28px;display:block}.note{background:#f4f6f8;padding:18px}pre{white-space:pre-wrap;font-size:12px}footer{border-top:1px solid #ddd;margin-top:30px;padding-top:20px}@media print{body{margin:10mm;max-width:none}h2,table{break-inside:avoid}}</style><small>MATHTECH / FACESCOPE · ANALYSIS REPORT</small><h1>${escapeHTML(session.name)}</h1><p>${escapeHTML(session.created_at||new Date().toISOString())} · ${escapeHTML(session.source?.name||'Local source')}</p><div class="stats"><div><b>${sum.samples}</b>sampled frames</div><div><b>${sum.tracking_percent.toFixed(1)}%</b>tracking coverage</div><div><b>${sum.duration.toFixed(1)} s</b>sample span</div><div><b>${sum.blinks}</b>blink events</div></div><h2>Raw geometric measurements</h2><table><thead><tr><th>Measurement</th><th>Mean</th><th>Minimum</th><th>Maximum</th></tr></thead><tbody>${rows}</tbody></table><h2>Event log</h2><table><tr><th>Time (s)</th><th>Event</th><th>Duration (s)</th></tr>${(session.events||[]).map(e=>`<tr><td>${fmt(e.time)}</td><td>${escapeHTML(e.type)}</td><td>${fmt(e.duration)}</td></tr>`).join('')||'<tr><td colspan="3">No detected events.</td></tr>'}</table><h2>Reproducibility</h2><pre>${escapeHTML(JSON.stringify({engine:session.engine,settings:session.settings,calibration:session.calibration,source:session.source},null,2))}</pre><div class="note">Tracking coverage is not an accuracy score. Eye and mouth values are unitless ratios. Head pose is a model-based estimate in degrees; iris values are relative positions, not calibrated screen gaze. Blendshape coefficients do not establish emotions or medical conditions. Uploaded footage with burned-in overlays may affect detection. This report contains raw measurements; neutral offsets and display smoothing do not alter them.</div><footer>Prepared with MathTech FaceScope · Shivam Singh, Founder of MathTech<br>Print this file from your browser to save as PDF.</footer></html>`;
}
export function exportSession(session,format) {
  const stem=(session.name||'facescope').replace(/[^a-zA-Z0-9_-]+/g,'-').slice(0,70)||'facescope';
  if(format==='csv')download(toCSV(session.samples),stem+'.csv','text/csv;charset=utf-8');
  if(format==='json')download(JSON.stringify(session,null,2),stem+'.json');
  if(format==='report')download(reportHTML(session),stem+'-report.html','text/html;charset=utf-8');
}
